version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - db_network
  python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8080
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network: