version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - db_network
  api:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    command: uvicorn --host=0.0.0.0 --port 8080 api:app --reload
    env_file:
      - .env
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
  kafka-consumer:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    command: >
      sh -c "/app/wait-for-it.sh api:8080 -- python -u main.py"    
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network:
